### PR TITLE
organise files into folders, add base components, add functionality f…

### PR DESCRIPTION
**Pull request by ProdiGeeZ**
…or GET /api/articles, clean up imports using index file, add index file for endpoints

### CODE REVIEW

**Review by nc-nick-jones — CHANGES_REQUESTED** [review]
Good work mohammed.  Some feedback - 
Can you extract your api calls into a separate js file?
Also can you please add a loading pattern?  Please resubmit when ready...

**Comment by ProdiGeeZ** [comment]
I've added a loading bar, the endpoints are in the previous commit under endpoints.js

**Review by nc-ali-abdallah — APPROVED** [review]
Nice job, lovely little loading bar.

Please make sure you're sticking to what the current ticket is asking for there is a lot of code here for things that will be addressed in later tickets and it makes it difficult to keep track of what code is for what ticket.

What Nick was asking for was that not just your URL's being in their own file. But that have you have a file which contain functions which call your api. getAllArticles() for example.

Merge when ready.

**Comment by ProdiGeeZ** [comment]
Ahhh i see, I'll add another file for this. Thanks Ali!

**Pull request merged**
